### ISSUE TITLE
Create the basic logic of the app that runs in the console 

### ISSUE THREAD

**Issue by aarijokhan** [aarijokhan/ssh-group-order-repo#1]
### Sub-tasks 

- [x] Develop logic for the marketplace tab
- [x] Develop logic for the profile tab
- [x] Develop logic for cart
- [x] Develop logic for wallet
- [x] Develop logic for order summary 
- [x] Develop logic for main menu
