### ISSUE TITLE
Create and populate database

### ISSUE THREAD

**Issue by aarijokhan** [aarijokhan/ssh-group-order-repo#2]
### Sub-tasks

- [x] Create and design the database 
- [x] Generate sample csv file
- [x] Connect database to the console backend to fetch the products 
- [x] Look into how we can host the database
