### ISSUE TITLE
Implement front-end 

### ISSUE THREAD

**Issue by aarijokhan** [aarijokhan/ssh-group-order-repo#3]
### Sub-tasks

- [x] Create the basic homepage
- [x] Create the group order section
- [x] Create marketplace section
- [x] Create navigator for screens
- [x] Create group order button
- [x] Simulate create/join group

**Comment by Fizan27** [comment]
Completed all tasks
